version: '3'
services: 
    db: 
        image: postgres
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: pix-challenge
            PGDATA: /var/lib/postgresql/data/pgdata
    app: 
        build: ./
        command: npm run dev
        ports: 
            - 3000:3000
        environment: 
            PORT: 3000
        links: 
            - db
        depends_on:
            - db
        volumes:
            - .:/app/
