# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  runner-job:
    name: Checking code
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: pix-challenge
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Nodejs 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          
      - name: Install all dependencies
        uses: Borales/actions-yarn@v2.3.0
        
      - name: Run type checking 
        run: yarn tsc
      
      - name: Run migrations
        run: yarn typeorm migration:run
        
      - name: Run tests
        run: yarn test
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PASSWORD: pix-challenge
      DB_USER: postgres
